[package]
name = "portfolio_rust"
version = "0.1.0"
authors = ["Jorn van Wier <jornvanwier@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]